// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcGt8zoYfsSKrdDDfvqmIqSe29xcZXOA4',
    appId: '1:73270994115:web:ff0a6e7dd06bdb0c11ee76',
    messagingSenderId: '73270994115',
    projectId: 'flutter3-68f08',
    authDomain: 'flutter3-68f08.firebaseapp.com',
    storageBucket: 'flutter3-68f08.appspot.com',
    measurementId: 'G-ZSR4Q71W2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4WBoC6oVZbEpnCb0ba4kn5ibXuOmZ9zg',
    appId: '1:73270994115:android:7acb5c35c8dd4c0e11ee76',
    messagingSenderId: '73270994115',
    projectId: 'flutter3-68f08',
    storageBucket: 'flutter3-68f08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJBXJs-dmzI0iRxi5vcg7POtsrQiZzdII',
    appId: '1:73270994115:ios:f25d84971a1ed23b11ee76',
    messagingSenderId: '73270994115',
    projectId: 'flutter3-68f08',
    storageBucket: 'flutter3-68f08.appspot.com',
    iosClientId: '73270994115-8jlbdcdhnv2n6jp1la9ibodv8m1mp5ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttterFire3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJBXJs-dmzI0iRxi5vcg7POtsrQiZzdII',
    appId: '1:73270994115:ios:f25d84971a1ed23b11ee76',
    messagingSenderId: '73270994115',
    projectId: 'flutter3-68f08',
    storageBucket: 'flutter3-68f08.appspot.com',
    iosClientId: '73270994115-8jlbdcdhnv2n6jp1la9ibodv8m1mp5ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttterFire3',
  );
}
